"""Add indexes in complaints table

Revision ID: 08f477671ff9
Revises: 15447ba8444a
Create Date: 2025-10-16 18:33:56.733088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f477671ff9'
down_revision = '15447ba8444a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_index('idx_complaints_district', ['district_id'], unique=False)
        batch_op.create_index('idx_complaints_hospital', ['hospital_id'], unique=False)
        batch_op.create_index('idx_complaints_state', ['state_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_index('idx_complaints_state')
        batch_op.drop_index('idx_complaints_hospital')
        batch_op.drop_index('idx_complaints_district')

    # ### end Alembic commands ###
