"""create user and complaint table

Revision ID: 15447ba8444a
Revises: dad18ec140fa
Create Date: 2025-10-16 11:51:56.128722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15447ba8444a'
down_revision = 'dad18ec140fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=False)

    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.district_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_mobile'), ['mobile'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_mobile'))

    op.drop_table('complaint')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))

    op.drop_table('user')
    # ### end Alembic commands ###
