"""Create hospital and category tables

Revision ID: 1bcee4ebb172
Revises: 
Create Date: 2025-10-08 20:18:56.756941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcee4ebb172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('hospital',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('hosp_disp_code', sa.String(length=100), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('mco_contact_number', sa.String(length=50), nullable=True),
    sa.Column('total_beds', sa.Integer(), nullable=True),
    sa.Column('hospital_type', sa.String(length=100), nullable=True),
    sa.Column('government_sub_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id', 'state')
    )
    op.create_table('hospital_category',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id', 'state'], ['hospital.hospital_id', 'hospital.state'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hospital_id', 'state', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_category')
    op.drop_table('hospital')
    op.drop_table('category')
    # ### end Alembic commands ###
