"""create hospital, category and association table

Revision ID: dad18ec140fa
Revises: 
Create Date: 2025-10-16 09:35:16.488695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad18ec140fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('state_name')
    )
    op.create_table('district',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_persons', sa.Integer(), nullable=True),
    sa.Column('total_males', sa.Integer(), nullable=True),
    sa.Column('total_females', sa.Integer(), nullable=True),
    sa.Column('children_persons', sa.Integer(), nullable=True),
    sa.Column('children_males', sa.Integer(), nullable=True),
    sa.Column('children_females', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('district_id')
    )
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_district_name'), ['district_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_district_state_id'), ['state_id'], unique=False)

    op.create_table('hospital',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('hospital_name', sa.String(length=1024), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('mco_contact_number', sa.String(length=50), nullable=True),
    sa.Column('total_beds', sa.Integer(), nullable=True),
    sa.Column('hospital_type', sa.String(length=100), nullable=True),
    sa.Column('government_subtype', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.district_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hospital_id', 'state_id')
    )
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_state_id'), ['state_id'], unique=False)

    op.create_table('hospital_category',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id', 'state_id'], ['hospital.hospital_id', 'hospital.state_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hospital_id', 'state_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_category')
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_state_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_district_id'))

    op.drop_table('hospital')
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_state_id'))
        batch_op.drop_index(batch_op.f('ix_district_district_name'))

    op.drop_table('district')
    op.drop_table('state')
    op.drop_table('category')
    # ### end Alembic commands ###
